"""
All business types and cities/timezones config.
Cities are ordered smaller-first to avoid burning through big metros early.
"""

BUSINESS_TYPES = [
    # Home & Property
    "HVAC Contractors",
    "Plumbing Services",
    "Electricians",
    "Roofing Contractors",
    "Pest Control Services",
    "Garage Door Repair",
    "Window Cleaning Services",
    "Carpet Cleaning Services",
    "House Cleaning Services",
    "Pool Maintenance",
    "Landscaping Services",
    "Tree Removal Services",
    "Driveway Paving",
    "Fencing Installation",
    "Deck Builders",
    "Gutter Cleaning",
    "Siding Contractors",
    "Painting Contractors",
    "Foundation Repair",
    "Water Damage Restoration",
    "Mold Remediation",
    "Junk Removal Services",
    "Handyman Services",
    "Septic Tank Services",
    "Chimney Sweep Services",
    "Custom Cabinetry",
    "Flooring Installation",
    "Solar Panel Installation",
    "General Contractors",
    "Appliance Repair",
    # Health & Wellness
    "Dental Clinics",
    "Orthodontists",
    "Chiropractors",
    "Physical Therapy Clinics",
    "Med Spas",
    "Dermatology Clinics",
    "Optometrists",
    "Podiatrists",
    "Veterinary Clinics",
    "Massage Therapy",
    "Acupuncture Clinics",
    "Audiologists",
    "Fertility Clinics",
    "Mental Health Counseling",
    "Mobile IV Therapy",
    "Sleep Clinics",
    "Pediatric Offices",
    "Orthopedic Clinics",
    "Urgent Care Centers",
    # Professional & Legal
    "Personal Injury Law Firms",
    "Family Law Attorneys",
    "Estate Planning Attorneys",
    "Criminal Defense Attorneys",
    "Immigration Law Firms",
    "CPA Tax Preparation",
    "Bookkeeping Services",
    "Financial Advisors",
    "Notary Public Services",
    "Bail Bondsmen",
    "Private Investigators",
    "Commercial Insurance Agencies",
    # Auto & Transport
    "Auto Repair Shops",
    "Auto Body Repair",
    "Auto Detailing",
    "Towing Companies",
    "Auto Glass Repair",
    "Transmission Shops",
    "Tire Shops",
    "RV Repair",
    "Boat Repair",
    "Local Moving Companies",
    "Long Distance Moving Companies",
    "Freight Brokers",
    "Fleet Maintenance",
    # Real Estate & Events
    "Property Management Companies",
    "Real Estate Brokerages",
    "Title Companies",
    "Home Inspection Services",
    "Real Estate Appraisers",
    "Mortgage Brokers",
    "Storage Facilities",
    "Wedding Venues",
    "Event Planners",
    "Catering Companies",
    "Party Rental Services",
    "Florists",
    "Photography Studios",
    # Personal & Beauty
    "Hair Salons",
    "Barbershops",
    "Nail Salons",
    "Tattoo Parlors",
    "Dog Daycare",
    "Pet Grooming",
    "Dog Training",
    "Tailors",
    "Dry Cleaning",
    "Crossfit Gyms",
    "Personal Training Studios",
    "Martial Arts Schools",
    "Funeral Homes",
]

# (city, state_province, country, timezone)
# Ordered smaller cities first within each timezone
CITIES = [
    # --- EST smaller ---
    ("Providence", "RI", "USA", "EST"),
    ("Charleston", "SC", "USA", "EST"),
    ("Louisville", "KY", "USA", "EST"),
    ("Richmond", "VA", "USA", "EST"),
    ("Grand Rapids", "MI", "USA", "EST"),
    ("Worcester", "MA", "USA", "EST"),
    ("Savannah", "GA", "USA", "EST"),
    ("Buffalo", "NY", "USA", "EST"),
    ("Pittsburgh", "PA", "USA", "EST"),
    ("Cincinnati", "OH", "USA", "EST"),
    ("Cleveland", "OH", "USA", "EST"),
    ("Columbus", "OH", "USA", "EST"),
    ("Indianapolis", "IN", "USA", "EST"),
    # --- EST Canada smaller ---
    ("Hamilton", "ON", "Canada", "EST"),
    ("London", "ON", "Canada", "EST"),
    ("Ottawa", "ON", "Canada", "EST"),
    ("Quebec City", "QC", "Canada", "EST"),
    ("Mississauga", "ON", "Canada", "EST"),
    # --- EST larger ---
    ("Baltimore", "MD", "USA", "EST"),
    ("Jacksonville", "FL", "USA", "EST"),
    ("Tampa", "FL", "USA", "EST"),
    ("Orlando", "FL", "USA", "EST"),
    ("Charlotte", "NC", "USA", "EST"),
    ("Raleigh", "NC", "USA", "EST"),
    ("Washington", "DC", "USA", "EST"),
    ("Detroit", "MI", "USA", "EST"),
    ("Atlanta", "GA", "USA", "EST"),
    ("Miami", "FL", "USA", "EST"),
    ("Philadelphia", "PA", "USA", "EST"),
    ("Boston", "MA", "USA", "EST"),
    ("New York City", "NY", "USA", "EST"),
    ("Toronto", "ON", "Canada", "EST"),
    ("Montreal", "QC", "Canada", "EST"),
    # --- CST smaller ---
    ("Jackson", "MS", "USA", "CST"),
    ("Little Rock", "AR", "USA", "CST"),
    ("Des Moines", "IA", "USA", "CST"),
    ("Madison", "WI", "USA", "CST"),
    ("Omaha", "NE", "USA", "CST"),
    ("Tulsa", "OK", "USA", "CST"),
    ("Baton Rouge", "LA", "USA", "CST"),
    ("Peoria", "IL", "USA", "CST"),
    ("St. Paul", "MN", "USA", "CST"),
    ("Regina", "SK", "Canada", "CST"),
    ("Winnipeg", "MB", "Canada", "CST"),
    # --- CST larger ---
    ("Birmingham", "AL", "USA", "CST"),
    ("Memphis", "TN", "USA", "CST"),
    ("Nashville", "TN", "USA", "CST"),
    ("New Orleans", "LA", "USA", "CST"),
    ("Oklahoma City", "OK", "USA", "CST"),
    ("Kansas City", "MO", "USA", "CST"),
    ("St. Louis", "MO", "USA", "CST"),
    ("Milwaukee", "WI", "USA", "CST"),
    ("Minneapolis", "MN", "USA", "CST"),
    ("San Antonio", "TX", "USA", "CST"),
    ("Austin", "TX", "USA", "CST"),
    ("Fort Worth", "TX", "USA", "CST"),
    ("Dallas", "TX", "USA", "CST"),
    ("Houston", "TX", "USA", "CST"),
    ("Chicago", "IL", "USA", "CST"),
    # --- MST smaller ---
    ("Cheyenne", "WY", "USA", "MST"),
    ("Santa Fe", "NM", "USA", "MST"),
    ("Billings", "MT", "USA", "MST"),
    ("Boise", "ID", "USA", "MST"),
    ("Provo", "UT", "USA", "MST"),
    ("Tucson", "AZ", "USA", "MST"),
    ("Scottsdale", "AZ", "USA", "MST"),
    ("Boulder", "CO", "USA", "MST"),
    ("Colorado Springs", "CO", "USA", "MST"),
    ("Albuquerque", "NM", "USA", "MST"),
    ("Edmonton", "AB", "Canada", "MST"),
    ("Calgary", "AB", "Canada", "MST"),
    ("Salt Lake City", "UT", "USA", "MST"),
    ("Phoenix", "AZ", "USA", "MST"),
    ("Denver", "CO", "USA", "MST"),
    # --- PST smaller ---
    ("Victoria", "BC", "Canada", "PST"),
    ("Kelowna", "BC", "Canada", "PST"),
    ("Eugene", "OR", "USA", "PST"),
    ("Reno", "NV", "USA", "PST"),
    ("Spokane", "WA", "USA", "PST"),
    ("Tacoma", "WA", "USA", "PST"),
    ("Surrey", "BC", "Canada", "PST"),
    ("Sacramento", "CA", "USA", "PST"),
    ("Portland", "OR", "USA", "PST"),
    ("Las Vegas", "NV", "USA", "PST"),
    ("San Jose", "CA", "USA", "PST"),
    ("San Diego", "CA", "USA", "PST"),
    ("Vancouver", "BC", "Canada", "PST"),
    ("Seattle", "WA", "USA", "PST"),
    ("San Francisco", "CA", "USA", "PST"),
    ("Los Angeles", "CA", "USA", "PST"),
]

CSV_COLUMNS = [
    "Business Name", "City", "Contact Name", "Country", "Deal Value",
    "Email", "Facebook", "Industry", "Instagram", "Last Contact Date",
    "LinkedIn", "Next Follow Up Date", "Offer Discussed", "Opener Note",
    "Phone", "State / Province", "Status", "Timezone", "Total Calls Made", "Website"
]
